# Explanation of parameters: https://docs.nav2.org/configuration/packages/configuring-bt-navigator.html
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /warehouse_bot_controller/odom
    transform_tolerance: 0.3
    default_server_timeout: 1000
    bt_loop_duration: 10
    wait_for_service_timeout: 1000
    default_nav_to_pose_bt_xml: "/media/mikelap/DATA2/Development/GithubRepos/robotics-sim-projects/warehouse_ws/src/warehouse_bot_navigation/behaviour_tree/bt_navigation.xml"
    default_nav_through_poses_bt_xml: "/media/mikelap/DATA2/Development/GithubRepos/robotics-sim-projects/warehouse_ws/src/warehouse_bot_navigation/behaviour_tree/bt_navigation.xml"
